run:
  skip-files:
    - migration/sqlbindata.go
  skip-dirs:
    - design/*
linters:
  fast: true
service:
  project-path: github.com/fabric8-services/fabric8-build
  prepare:
    - make deps generate
